#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# @Author   : lisztomania
# @Date     : 2021/2/4
# @Software : Pycharm
# @Version  : Python 3.8.5
# @File     : Task_Exception.py
# @Function : 任务异常

class TASK_EXCEPTION(Exception):
    pass
